package GUI;



import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hala
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        map1.setVisible(false);
        health1.setVisible(false);
        police1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        map1 = new javax.swing.JLabel();
        health1 = new javax.swing.JLabel();
        police1 = new javax.swing.JLabel();
        police = new javax.swing.JLabel();
        health = new javax.swing.JLabel();
        map = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        map1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/light.png"))); // NOI18N
        map1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                map1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                map1MouseExited(evt);
            }
        });
        getContentPane().add(map1);
        map1.setBounds(170, 140, 270, 210);

        health1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/light.png"))); // NOI18N
        health1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                health1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                health1MouseExited(evt);
            }
        });
        getContentPane().add(health1);
        health1.setBounds(290, 140, 270, 210);

        police1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/light.png"))); // NOI18N
        police1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                police1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                police1MouseExited(evt);
            }
        });
        getContentPane().add(police1);
        police1.setBounds(410, 140, 270, 210);

        police.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\dark.png")); // NOI18N
        police.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                policeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                policeMouseExited(evt);
            }
        });
        getContentPane().add(police);
        police.setBounds(450, 140, 270, 210);

        health.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\dark.png")); // NOI18N
        health.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                healthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                healthMouseExited(evt);
            }
        });
        getContentPane().add(health);
        health.setBounds(330, 140, 270, 210);

        map.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\dark.png")); // NOI18N
        map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mapMouseExited(evt);
            }
        });
        getContentPane().add(map);
        map.setBounds(210, 140, 270, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Background.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 830, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapMouseEntered
       //map.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\light.png"));
       //health.setVisible(false);
       //police.setVisible(false);
       map.setVisible(false);
       map1.setVisible(true);
    }//GEN-LAST:event_mapMouseEntered

    private void healthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthMouseEntered
       //health.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\light.png"));
       //map.setVisible(false);
       //police.setVisible(false);
        health.setVisible(false);
        health1.setVisible(true);
    }//GEN-LAST:event_healthMouseEntered

    private void policeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeMouseEntered
       //police.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\light.png"));
       //map.setVisible(false);
       //health.setVisible(false);
        police.setVisible(false);
       police1.setVisible(true);
    }//GEN-LAST:event_policeMouseEntered

    private void mapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapMouseExited
       //map.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\dark.png"));
       //health.setVisible(true);
       //police.setVisible(true);
        map1.setVisible(false);
        map.setVisible(true);
    }//GEN-LAST:event_mapMouseExited

    private void healthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthMouseExited
       //health.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\dark.png"));
       //map.setVisible(true);
       //police.setVisible(true);
        health1.setVisible(false);
       health.setVisible(true);
    }//GEN-LAST:event_healthMouseExited

    private void policeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeMouseExited
        //police.setIcon(new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\Hajj\\src\\dark.png"));
        //map.setVisible(true);
        //health.setVisible(true);
        police1.setVisible(false);
        police.setVisible(true);
    }//GEN-LAST:event_policeMouseExited

    private void map1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_map1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_map1MouseEntered

    private void map1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_map1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_map1MouseExited

    private void health1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_health1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_health1MouseEntered

    private void health1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_health1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_health1MouseExited

    private void police1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_police1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_police1MouseEntered

    private void police1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_police1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_police1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel health;
    private javax.swing.JLabel health1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel map;
    private javax.swing.JLabel map1;
    private javax.swing.JLabel police;
    private javax.swing.JLabel police1;
    // End of variables declaration//GEN-END:variables
}
