/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import static volanteer.volanteerInterface.hajj_id;

/**
 *
 * @author Hala
 */
public class myInfo extends javax.swing.JFrame {

    /**
     * Creates new form myInfo
     */
    public static String hajj_id;
    public myInfo() {
        initComponents();
         normal();

        volanteer.connection c = new volanteer.connection();
        String x = "v";
        ResultSet result1 = volanteer.connection.setQuery("SELECT hajj_id from notification where type = '" + x + "'");
        try {
            //System.out.println("beyy");
            while (result1.next()) {
                //System.out.println("hii");
                hajj_id = result1.getString("hajj_id");
                //System.out.println("nnnnnnn "+ hajj_id);
            }
        } catch (SQLException ex) {
            System.out.println("cant");
        }

        ResultSet result2 = volanteer.connection.setQuery("SELECT * from hajj_info where id = " + hajj_id);
        try {
            //System.out.println("beyy");
            while (result2.next()) {
                name3.setText(result2.getString("full_name"));
                nationality3.setText(result2.getString("nationality"));
                age3.setText(result2.getString("age"));
                
                byte [] img = result2.getBytes("photo");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                imageLabel.setIcon(newImage);

            }
        } catch (SQLException ex) {
            System.out.println("cant");
        }

        ResultSet result3 = volanteer.connection.setQuery("SELECT * from campaign_info where hajj_id = " + hajj_id);
        try {
            //System.out.println("beyy");
            while (result3.next()) {
                travel2.setText(result3.getString("campaign_name"));
                Campaign_guide.setText(result3.getString("supervisor_phone"));
            }
        } catch (SQLException ex) {
            System.out.println("cant");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mina22 = new javax.swing.JLabel();
        mozd22 = new javax.swing.JLabel();
        mina_big_border = new javax.swing.JLabel();
        arafa22 = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        supervisor = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        hotel = new javax.swing.JLabel();
        hotelPhone = new javax.swing.JLabel();
        supervisorPhone = new javax.swing.JLabel();
        moz_big_border = new javax.swing.JLabel();
        makkah22 = new javax.swing.JLabel();
        mozd11 = new javax.swing.JLabel();
        arafat_big_border = new javax.swing.JLabel();
        makkah_big_border = new javax.swing.JLabel();
        arafa11 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        moz_small_border = new javax.swing.JLabel();
        travel2 = new javax.swing.JLabel();
        mina11 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        age3 = new javax.swing.JLabel();
        Campaign_guide = new javax.swing.JLabel();
        madina22 = new javax.swing.JLabel();
        nationality3 = new javax.swing.JLabel();
        madina_big_border = new javax.swing.JLabel();
        makkah11 = new javax.swing.JLabel();
        madina11 = new javax.swing.JLabel();
        mina_small_border = new javax.swing.JLabel();
        arafat_small_border = new javax.swing.JLabel();
        makkah_small_border = new javax.swing.JLabel();
        madina_small_border = new javax.swing.JLabel();
        Accommodation1 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        imgFrameLabel = new javax.swing.JLabel();
        nationality4 = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mina22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        mina22.setForeground(new java.awt.Color(0, 204, 255));
        mina22.setText("Mina");
        getContentPane().add(mina22);
        mina22.setBounds(390, 370, 60, 40);

        mozd22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        mozd22.setForeground(new java.awt.Color(0, 204, 255));
        mozd22.setText("Mozdlifa");
        getContentPane().add(mozd22);
        mozd22.setBounds(310, 370, 80, 40);

        mina_big_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture6.png"))); // NOI18N
        mina_big_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mina_big_borderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mina_big_borderMouseExited(evt);
            }
        });
        getContentPane().add(mina_big_border);
        mina_big_border.setBounds(360, 350, 110, 80);

        arafa22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        arafa22.setForeground(new java.awt.Color(0, 204, 255));
        arafa22.setText("Arafat");
        getContentPane().add(arafa22);
        arafa22.setBounds(250, 370, 80, 40);

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setLayout(null);

        supervisor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        supervisor.setForeground(new java.awt.Color(255, 255, 255));
        supervisor.setText("0556544343");
        supervisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoPanel.add(supervisor);
        supervisor.setBounds(10, 110, 330, 20);

        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 255));
        title.setText("MADINA");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoPanel.add(title);
        title.setBounds(10, 13, 230, 22);

        hotel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hotel.setForeground(new java.awt.Color(255, 255, 255));
        hotel.setText("Ajyad Hotel");
        hotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoPanel.add(hotel);
        hotel.setBounds(10, 50, 330, 20);

        hotelPhone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hotelPhone.setForeground(new java.awt.Color(255, 255, 255));
        hotelPhone.setText("Street ajyad,ffugij");
        hotelPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoPanel.add(hotelPhone);
        hotelPhone.setBounds(10, 70, 330, 20);

        supervisorPhone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        supervisorPhone.setForeground(new java.awt.Color(255, 255, 255));
        supervisorPhone.setText("0556544343");
        supervisorPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoPanel.add(supervisorPhone);
        supervisorPhone.setBounds(10, 130, 330, 20);

        getContentPane().add(infoPanel);
        infoPanel.setBounds(110, 150, 330, 200);

        moz_big_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture6.png"))); // NOI18N
        moz_big_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moz_big_borderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moz_big_borderMouseExited(evt);
            }
        });
        getContentPane().add(moz_big_border);
        moz_big_border.setBounds(290, 350, 110, 80);

        makkah22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        makkah22.setForeground(new java.awt.Color(0, 204, 255));
        makkah22.setText("Makkah");
        getContentPane().add(makkah22);
        makkah22.setBounds(170, 370, 80, 40);

        mozd11.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        mozd11.setForeground(new java.awt.Color(0, 204, 255));
        mozd11.setText("Mozdlifa");
        getContentPane().add(mozd11);
        mozd11.setBounds(320, 380, 60, 30);

        arafat_big_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture6.png"))); // NOI18N
        arafat_big_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arafat_big_borderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arafat_big_borderMouseExited(evt);
            }
        });
        getContentPane().add(arafat_big_border);
        arafat_big_border.setBounds(220, 350, 110, 80);

        makkah_big_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture6.png"))); // NOI18N
        makkah_big_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makkah_big_borderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                makkah_big_borderMouseExited(evt);
            }
        });
        getContentPane().add(makkah_big_border);
        makkah_big_border.setBounds(150, 350, 110, 80);

        arafa11.setFont(new java.awt.Font("Segoe Print", 3, 13)); // NOI18N
        arafa11.setForeground(new java.awt.Color(0, 204, 255));
        arafa11.setText("Arafat");
        getContentPane().add(arafa11);
        arafa11.setBounds(250, 380, 50, 30);
        getContentPane().add(imageLabel);
        imageLabel.setBounds(490, 190, 100, 90);

        moz_small_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture7.png"))); // NOI18N
        moz_small_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moz_small_borderMouseEntered(evt);
            }
        });
        getContentPane().add(moz_small_border);
        moz_small_border.setBounds(300, 360, 80, 70);

        travel2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        travel2.setForeground(new java.awt.Color(255, 255, 255));
        travel2.setText("Name:");
        getContentPane().add(travel2);
        travel2.setBounds(250, 310, 210, 20);

        mina11.setFont(new java.awt.Font("Segoe Print", 3, 13)); // NOI18N
        mina11.setForeground(new java.awt.Color(0, 204, 255));
        mina11.setText("Mina");
        getContentPane().add(mina11);
        mina11.setBounds(400, 380, 40, 30);

        name3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("Name:");
        getContentPane().add(name3);
        name3.setBounds(170, 150, 280, 20);

        age3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        age3.setForeground(new java.awt.Color(255, 255, 255));
        age3.setText("Name:");
        getContentPane().add(age3);
        age3.setBounds(160, 230, 260, 20);

        Campaign_guide.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        Campaign_guide.setForeground(new java.awt.Color(255, 255, 255));
        Campaign_guide.setText("Name:");
        getContentPane().add(Campaign_guide);
        Campaign_guide.setBounds(250, 270, 220, 20);

        madina22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        madina22.setForeground(new java.awt.Color(0, 204, 255));
        madina22.setText("Madina");
        getContentPane().add(madina22);
        madina22.setBounds(100, 370, 70, 40);

        nationality3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        nationality3.setForeground(new java.awt.Color(255, 255, 255));
        nationality3.setText("Name:");
        getContentPane().add(nationality3);
        nationality3.setBounds(210, 190, 240, 20);

        madina_big_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture6.png"))); // NOI18N
        madina_big_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                madina_big_borderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                madina_big_borderMouseExited(evt);
            }
        });
        getContentPane().add(madina_big_border);
        madina_big_border.setBounds(80, 350, 110, 80);

        makkah11.setFont(new java.awt.Font("Segoe Print", 3, 13)); // NOI18N
        makkah11.setForeground(new java.awt.Color(0, 204, 255));
        makkah11.setText("Makkah");
        getContentPane().add(makkah11);
        makkah11.setBounds(180, 380, 60, 30);

        madina11.setFont(new java.awt.Font("Segoe Print", 3, 13)); // NOI18N
        madina11.setForeground(new java.awt.Color(0, 204, 255));
        madina11.setText("Madina");
        madina11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                madina11MouseEntered(evt);
            }
        });
        getContentPane().add(madina11);
        madina11.setBounds(110, 380, 50, 30);

        mina_small_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture7.png"))); // NOI18N
        mina_small_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mina_small_borderMouseEntered(evt);
            }
        });
        getContentPane().add(mina_small_border);
        mina_small_border.setBounds(370, 360, 80, 70);

        arafat_small_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture7.png"))); // NOI18N
        arafat_small_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arafat_small_borderMouseEntered(evt);
            }
        });
        getContentPane().add(arafat_small_border);
        arafat_small_border.setBounds(230, 360, 80, 70);

        makkah_small_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture7.png"))); // NOI18N
        makkah_small_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makkah_small_borderMouseEntered(evt);
            }
        });
        getContentPane().add(makkah_small_border);
        makkah_small_border.setBounds(160, 360, 80, 70);

        madina_small_border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture7.png"))); // NOI18N
        madina_small_border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                madina_small_borderMouseEntered(evt);
            }
        });
        getContentPane().add(madina_small_border);
        madina_small_border.setBounds(90, 360, 80, 70);

        Accommodation1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        Accommodation1.setForeground(new java.awt.Color(0, 204, 255));
        Accommodation1.setText("Campaign guide:");
        getContentPane().add(Accommodation1);
        Accommodation1.setBounds(120, 270, 130, 30);

        age.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 204, 255));
        age.setText("Age:");
        getContentPane().add(age);
        age.setBounds(120, 230, 120, 20);

        imgFrameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Picture12.png"))); // NOI18N
        getContentPane().add(imgFrameLabel);
        imgFrameLabel.setBounds(480, 180, 130, 110);

        nationality4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        nationality4.setForeground(new java.awt.Color(0, 204, 255));
        nationality4.setText("Travel campaign:");
        getContentPane().add(nationality4);
        nationality4.setBounds(120, 310, 160, 30);

        nationality.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        nationality.setForeground(new java.awt.Color(0, 204, 255));
        nationality.setText("Nationality:");
        getContentPane().add(nationality);
        nationality.setBounds(120, 190, 90, 20);

        name.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 204, 255));
        name.setText("Name:");
        getContentPane().add(name);
        name.setBounds(120, 150, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_a.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel1KeyTyped(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mina_big_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mina_big_borderMouseEntered
        infoPanel.setVisible(true);
        title.setText("MINA");
        info("mina");
    }//GEN-LAST:event_mina_big_borderMouseEntered

    private void mina_big_borderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mina_big_borderMouseExited
        normal();
    }//GEN-LAST:event_mina_big_borderMouseExited

    private void moz_big_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moz_big_borderMouseEntered
        infoPanel.setVisible(true);
        title.setText("MOZDALIFA");
        info("mozd");
    }//GEN-LAST:event_moz_big_borderMouseEntered

    private void moz_big_borderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moz_big_borderMouseExited
        normal();
    }//GEN-LAST:event_moz_big_borderMouseExited

    private void arafat_big_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arafat_big_borderMouseEntered
        infoPanel.setVisible(true);
        title.setText("ARAFAT");
        info("arafat");
    }//GEN-LAST:event_arafat_big_borderMouseEntered

    private void arafat_big_borderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arafat_big_borderMouseExited
        normal();
    }//GEN-LAST:event_arafat_big_borderMouseExited

    private void makkah_big_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makkah_big_borderMouseEntered
        infoPanel.setVisible(true);
        title.setText("MAKKAH");
        info("makkah");
    }//GEN-LAST:event_makkah_big_borderMouseEntered

    private void makkah_big_borderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makkah_big_borderMouseExited
        normal();
    }//GEN-LAST:event_makkah_big_borderMouseExited

    private void moz_small_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moz_small_borderMouseEntered
        normal();
        mozd11.setVisible(false);
        mozd22.setVisible(true);
        moz_big_border.setVisible(true);
        moz_small_border.setVisible(false);
    }//GEN-LAST:event_moz_small_borderMouseEntered

    private void madina_big_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_madina_big_borderMouseEntered
        infoPanel.setVisible(true);
        title.setText("MADINA");
        info("madina");
    }//GEN-LAST:event_madina_big_borderMouseEntered

    private void madina_big_borderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_madina_big_borderMouseExited
        normal();
    }//GEN-LAST:event_madina_big_borderMouseExited

    private void madina11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_madina11MouseEntered
        normal();
        madina11.setVisible(false);
        madina22.setVisible(true);
        madina_big_border.setVisible(true);
        madina_small_border.setVisible(false);
    }//GEN-LAST:event_madina11MouseEntered

    private void mina_small_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mina_small_borderMouseEntered
        normal();
        mina11.setVisible(false);
        mina22.setVisible(true);
        mina_small_border.setVisible(false);
        mina_big_border.setVisible(true);
    }//GEN-LAST:event_mina_small_borderMouseEntered

    private void arafat_small_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arafat_small_borderMouseEntered
        normal();
        arafa11.setVisible(false);
        arafa22.setVisible(true);
        arafat_big_border.setVisible(true);
        arafat_small_border.setVisible(false);
    }//GEN-LAST:event_arafat_small_borderMouseEntered

    private void makkah_small_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makkah_small_borderMouseEntered
        normal();
        makkah11.setVisible(false);
        makkah22.setVisible(true);
        makkah_big_border.setVisible(true);
        makkah_small_border.setVisible(false);
    }//GEN-LAST:event_makkah_small_borderMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //        this.setVisible(false);
        //        menu Home = new menu();
        //        //left - up
        //        ImageIcon img = new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\icon.png");
        //        Home.setIconImage(img.getImage());
        //        Home.setBounds(255, 100, 825, 526);
        //        Home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //        Home.setVisible(true);
        //        Home.setResizable(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        //        this.setVisible(false);
        //        menu Home = new menu();
        //        //left - up
        //        ImageIcon img = new ImageIcon("C:\\Users\\Hala\\Desktop\\New folder\\icon.png");
        //        Home.setIconImage(img.getImage());
        //        Home.setBounds(255, 100, 825, 526);
        //        Home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //        Home.setVisible(true);
        //        Home.setResizable(true);
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyTyped
        //        this.setVisible(false);
        //        menu Home = new menu();
        //        //left - up
        //        ImageIcon img = new ImageIcon("icon.png");
        //        Home.setIconImage(img.getImage());
        //        Home.setBounds(255, 100, 825, 526);
        //        Home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //        Home.setVisible(true);
        //        Home.setResizable(true);
    }//GEN-LAST:event_jLabel1KeyTyped

    private void madina_small_borderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_madina_small_borderMouseEntered
         normal();
        madina11.setVisible(false);
        madina22.setVisible(true);
        madina_big_border.setVisible(true);
        madina_small_border.setVisible(false);
    }//GEN-LAST:event_madina_small_borderMouseEntered
 private void normal() {

        infoPanel.setVisible(false);

        madina_big_border.setVisible(false);
        makkah_big_border.setVisible(false);
        arafat_big_border.setVisible(false);
        moz_big_border.setVisible(false);
        mina_big_border.setVisible(false);

        madina_small_border.setVisible(true);
        makkah_small_border.setVisible(true);
        arafat_small_border.setVisible(true);
        moz_small_border.setVisible(true);
        mina_small_border.setVisible(true);

        madina22.setVisible(false);
        makkah22.setVisible(false);
        arafa22.setVisible(false);
        mozd22.setVisible(false);
        mina22.setVisible(false);

        madina11.setVisible(true);
        makkah11.setVisible(true);
        arafa11.setVisible(true);
        mozd11.setVisible(true);
        mina11.setVisible(true);
    }
  private void info(String place) {
        ResultSet result3 = volanteer.connection.setQuery("SELECT * from campaign_info where hajj_id = " + hajj_id);
        try {
            //System.out.println("beyy");
            while (result3.next()) {
                //travel2.setText(result3.getString("campaign_name"));
                switch (place) {
                    case "madina":
                        hotel.setText("Hotel: " + result3.getString("madina_hotel_name"));
                        hotelPhone.setText("Hotel No.: " + result3.getString("madina_hotel_phone"));
                        supervisor.setText("Supervisor Name: " + result3.getString("supervisor_name"));
                        supervisorPhone.setText("Supervisor No.: " + result3.getString("supervisor_phone"));
                        break;
                    case "makkah":
                        hotel.setText("Hotel: " + result3.getString("makkah_hotel_name"));
                        hotelPhone.setText("Hotel No.: " + result3.getString("makkah_hotel_phon"));
                        supervisor.setText("Supervisor Name: " + result3.getString("supervisor_name"));
                        supervisorPhone.setText("Supervisor No.: " + result3.getString("supervisor_phone"));
                        break;
                    case "arafat":
                        hotel.setText("Hotel: " + result3.getString("arafa_tent_no"));
                        // hotelPhone.setText("Hotel No.: "+result3.getString("madina_hotel_phone"));
                        supervisor.setText("Supervisor Name: " + result3.getString("supervisor_name"));
                        supervisorPhone.setText("Supervisor No.: " + result3.getString("supervisor_phone"));
                        break;
                    case "mozd":
                        hotel.setText("Tent No.: " + result3.getString("mozdalefa_tent_no"));
                        // hotelPhone.setText("Hotel No.: "+result3.getString("madina_hotel_phone"));
                        supervisor.setText("Supervisor Name: " + result3.getString("supervisor_name"));
                        supervisorPhone.setText("Supervisor No.: " + result3.getString("supervisor_phone"));
                        break;
                    case "mina":
                        hotel.setText("Hotel: " + result3.getString("mina_tent_no"));
                        //hotelPhone.setText("Hotel No.: "+result3.getString("madina_hotel_phone"));
                        supervisor.setText("Supervisor Name: " + result3.getString("supervisor_name"));
                        supervisorPhone.setText("Supervisor No.: " + result3.getString("supervisor_phone"));
                        break;
                }

            }
        } catch (SQLException ex) {
            System.out.println("cant");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accommodation1;
    private javax.swing.JLabel Campaign_guide;
    private javax.swing.JLabel age;
    private javax.swing.JLabel age3;
    private javax.swing.JLabel arafa11;
    private javax.swing.JLabel arafa22;
    private javax.swing.JLabel arafat_big_border;
    private javax.swing.JLabel arafat_small_border;
    private javax.swing.JLabel hotel;
    private javax.swing.JLabel hotelPhone;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imgFrameLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel madina11;
    private javax.swing.JLabel madina22;
    private javax.swing.JLabel madina_big_border;
    private javax.swing.JLabel madina_small_border;
    private javax.swing.JLabel makkah11;
    private javax.swing.JLabel makkah22;
    private javax.swing.JLabel makkah_big_border;
    private javax.swing.JLabel makkah_small_border;
    private javax.swing.JLabel mina11;
    private javax.swing.JLabel mina22;
    private javax.swing.JLabel mina_big_border;
    private javax.swing.JLabel mina_small_border;
    private javax.swing.JLabel moz_big_border;
    private javax.swing.JLabel moz_small_border;
    private javax.swing.JLabel mozd11;
    private javax.swing.JLabel mozd22;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel nationality;
    private javax.swing.JLabel nationality3;
    private javax.swing.JLabel nationality4;
    private javax.swing.JLabel supervisor;
    private javax.swing.JLabel supervisorPhone;
    private javax.swing.JLabel title;
    private javax.swing.JLabel travel2;
    // End of variables declaration//GEN-END:variables
}
